#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          prepare-dirs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:  
# Required-Stop:   
# Short-Description: Create gbmon directory on tmpfs at startup
# Description:       Create gbmon directory on tmpfs at startup
### END INIT INFO

DIRlog=/var/log/lighttpd
DIRweb=/var/www
DIRlive=/var/www/live/segments

gbmonGraphs=/home/pi/.gbmon/ramdisk/graphs
gbmonDB=/home/pi/.gbmon/ramdisk/db
gbmonPics=/home/pi/.gbmon/ramdisk/pics

#
# Installation:
# Copy/Put file to /etc/init.d/
# execute: 
# sudo chmod +x /etc/init.d/prepare-ramdisk
# sudo update-rc.d prepare-ramdisk defaults 01 99
#

#
# main()
#
case "${1:-''}" in
  start)
    # create the /var/log/lighttpd needed by webserver
    if [ ! -d ${DIRlog} ]; then
      mkdir ${DIRlog}
      chmod 755 ${DIRlog}
      chown -R www-data:www-data ${DIRlog}
    fi
	# create the /var/www/live/segments needed by live webserver
    if [ ! -d ${DIRlive} ]; then
      mkdir -p ${DIRlive}
      chmod 775 ${DIRlive}
      chown -R www-data:www-data ${DIRlive}
    fi
	# change permission of DIRweb
	# !! already exists due to command above !!
	chmod 775 ${DIRweb}
	chown -R www-data:www-data ${DIRweb}
	
	if [ ! -d ${gbmonDB} ]; then
      mkdir -p ${gbmonDB}
      chmod 750 ${gbmonDB}
      chown -R pi:www-data ${gbmonDB}
    fi

	if [ ! -d ${gbmonPics} ]; then
      mkdir -p ${gbmonPics}
      chmod 750 ${gbmonPics}
      chown -R pi:www-data ${gbmonPics}
    fi
	if [ ! -d ${gbmonGraphs} ]; then
      mkdir -p ${gbmonGraphs}
      chmod 750 ${gbmonGraphs}
      chown -R pi:www-data ${gbmonGraphs}
    fi
    ;;
  stop)
    ;;
  restart)
   ;;
  reload|force-reload)
   ;;
  status)
   ;;
  *)
   echo "Usage: $SELF start"
   exit 1
   ;;
esac
