#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          prepare-dirs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:  
# Required-Stop:   
# Short-Description: Create /var/log/lighttpd directory on tmpfs at startup
# Description:       Create /var/log/lighttpd directory on tmpfs at startup
### END INIT INFO

DIRlog=/var/log/lighttpd
DIRweb=/var/www
DIRlive=/var/www/live/segments

#
# Installation:
# Copy/Put file to /etc/init.d/
# execute: 
# update-rc.d prepare-dirs defaults 01 99
#

#
# main()
#
case "${1:-''}" in
  start)
    # create the /var/log/lighttpd needed by webserver
    if [ ! -d ${DIRlog} ]; then
      mkdir ${DIRlog}
      chmod 755 ${DIRlog}
      chown -R www-data:www-data ${DIRlog}
    fi
	# create the /var/www/live/segments needed by live webserver
    if [ ! -d ${DIRlive} ]; then
      mkdir -p ${DIRlive}
      chmod 775 ${DIRlive}
      chown -R www-data:www-data ${DIRlive}
    fi
	# change permission of DIRweb
	# !! already exists due to command above !!
	chmod 775 ${DIRweb}
	chown -R www-data:www-data ${DIRweb}
    ;;
  stop)
    ;;
  restart)
   ;;
  reload|force-reload)
   ;;
  status)
   ;;
  *)
   echo "Usage: $SELF start"
   exit 1
   ;;
esac
